* getting-started
How to get started using the humacs collaboration tools!

** OSX + Brew
*** Launch Terminal.app
~command-space~ ~Terminal.app~
*** Brew.sh
https://brew.sh is a package manager for OSX. This install can take a while, and will likely require your password a few times.
  #+begin_src shell
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  #+end_src
  
  #+begin_example
    ==> This script will install:
    /usr/local/bin/brew
    /usr/local/share/doc/homebrew
    /usr/local/share/man/man1/brew.1
    /usr/local/share/zsh/site-functions/_brew
    /usr/local/etc/bash_completion.d/brew
    /usr/local/Homebrew
    ==> The following new directories will be created:
    /usr/local/bin
    /usr/local/etc
    /usr/local/include
    /usr/local/lib
    /usr/local/sbin
    /usr/local/share
    /usr/local/var
    /usr/local/opt
    /usr/local/share/zsh
    /usr/local/share/zsh/site-functions
    /usr/local/var/homebrew
    /usr/local/var/homebrew/linked
    /usr/local/Cellar
    /usr/local/Caskroom
    /usr/local/Homebrew
    /usr/local/Frameworks
    ==> The Xcode Command Line Tools will be installed.

    Press RETURN to continue or any other key to abort
    Done with Command Line Tools for Xcode
    Done.
    ==> /usr/bin/sudo /bin/rm -f /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
    Password:
    ==> Installation successful!

    ==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
    Read the analytics documentation (and how to opt-out) here:
      https://docs.brew.sh/Analytics
    No analytics data has been sent yet (or will be during this `install` run).
    
    ==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
      https://github.com/Homebrew/brew#donations
    
    ==> Next steps:
    - Run `brew help` to get started
    - Further documentation: 
        https://docs.brew.sh
  #+end_example
  
  #+begin_example
  Password:
    ==> /usr/bin/sudo /bin/mkdir -p /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
    ==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
    ==> /usr/bin/sudo /usr/sbin/chown hh /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
    ==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
    ==> /usr/bin/sudo /bin/mkdir -p /Users/hh/Library/Caches/Homebrew
    ==> /usr/bin/sudo /bin/chmod g+rwx /Users/hh/Library/Caches/Homebrew
    ==> /usr/bin/sudo /usr/sbin/chown hh /Users/hh/Library/Caches/Homebrew
    ==> Searching online for the Command Line Tools
    ==> /usr/bin/sudo /usr/bin/touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
    ==> Installing Command Line Tools for Xcode-11.4
    ==> /usr/bin/sudo /usr/sbin/softwareupdate -i Command\ Line\ Tools\ for\ Xcode-11.4
    Software Update Tool
    
    
    Downloading Command Line Tools for Xcode
    Downloaded Command Line Tools for Xcode
    Installing Command Line Tools for Xcode
    ==> /usr/bin/sudo /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools
    ==> Downloading and installing Homebrew...
    ==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
      https://github.com/Homebrew/brew#donations
    ==> Tapping homebrew/core
    Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
  #+end_example
*** Emacs 26.2
Brew currently install emacs 26.3
  #+begin_src shell
    brew cask install emacs # the absolute minimum of vanilla emacs
  #+end_src
*** Humacs emacs config
  #+begin_src shell
    git clone --recursive https://github.com/humacs/.emacs.d.git ~/.emacs.d
  #+end_src
  a cache of the elisp packages can make the initial start time much lower
  #+begin_src shell
    curl -L https://storage.googleapis.com/apisnoop/dev/kubemacs-cache-0.9.32.tgz | tar --extract --directory ~/.emacs.d/
  #+end_src
*** tmate/tmux
  for local terminal+tab creation
  #+begin_src shell
    brew install tmux
  #+end_src
  for sharing terminal+tabs with others
  #+begin_src shell
    brew install tmate
  #+end_src
*** iTerm2 (a very nice terminal)
  #+begin_src shell
    brew cast install iterm2
  #+end_src
*** searching
  commands for fas integrated searching, used by emacs
  #+begin_src shell
    brew install the_silver_searcher ripgrep
  #+end_src
*** kubernetes related software
  for k8s development
  #+begin_src shell
    brew install kubectl kind go@1.14 jq
  #+end_src
  needed for many containery things
  #+begin_src shell
    brew cast install docker
  #+end_src

** OSX + MacPorts
*** xcode
Macports is another alternative to brew with a different community culture.
xcode is automatically installed if you use Brew.sh
https://guide.macports.org/#installing.xcode
  #+begin_src shell
    xcode-select --install
    sudo xcodebuild -license
  #+end_src
